name: 'Split ASU Packages'

on:
  push:
    branches:
      - WS2-1623
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          - local_path: 'asu_brand'
            split_repository: 'asu_brand_fork'

    steps:
      -   uses: "actions/checkout@v4.1.7"

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          # ↓ split "/web/modules/asu_modules/asu_brand" directory
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/asuwebplatforms/asu_brand repository
          repository_organization: 'travisbutterfield'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
#          repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "tbutterf"
          user_email: "tbutterf@asu.edu"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "/web/modules/asu_modules/asu_brand" directory
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/asuwebplatforms/asu_brand repository
          repository_organization: 'travisbutterfield'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          # repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "tbutterf"
          user_email: "tbutterf@asu.edu"
