name: 'Split ASU Packages'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  packages_split:
    if: github.repository == 'travisbutterfield/webspark-ci-fork'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          - local_path: 'asu_brand'
            split_repository: 'asu_brand_fork'
          - local_path: 'asu_user'
            split_repository: 'asu_user_fork'

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "asu_user_fork,asu_brand_fork"

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        env:
          GITHUB_TOKEN: x-access-token:${{ steps.app-token.outputs.token }}
        with:
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'
          repository_organization: 'travisbutterfield'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "ws2-release-bot"
          user_email: "ws2-release-bot@asu.edu"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        env:
          GITHUB_TOKEN: x-access-token:${{ steps.app-token.outputs.token }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'web/modules/asu_modules/${{ matrix.package.local_path }}'
          repository_organization: 'travisbutterfield'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "ws2-release-bot"
          user_email: "ws2-release-bot@asu.edu"
