name: 'Test different workflow'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: '/web/modules/asu_modules/asu_user' # the local path to the package which should be separated
            split_repository: 'https://github.com/travisbutterfield/asu_user_fork.git' # the target repository where the changed should be pushed
            default_branch: 'main' # the default branch of the package (most it is `main`)
          - local_path: '/web/modules/asu_modules/asu_brand'
            split_repository: 'https://github.com/travisbutterfield/asu_brand_fork.git'
            default_branch: 'main'
            
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "asu_user_fork,asu_brand_fork"
      - name: Set release version for branch or tag
        run: echo "RELEASE_VERSION=${{ github.ref }}" >> $GITHUB_ENV
        
      - uses: erkenes/monorepo-split-action@1.3.0
        with:
          access_token: 'x-access-token:${{ steps.app-token.outputs.token }}' # The access token for the repository
          repository_protocol: 'https://' # the protocol for cloning the mono-repository
          repository_host: 'github.com' # the host of the mono-repository
          repository_organization: 'travisbutterfield' # the organization of the mono-repository
          repository_name: 'webspark-ci-fork' # the name of the mono-repository
          default_branch: '${{ matrix.package.default_branch }}' # default branch from the matrix
          target_branch: '${{ env.RELEASE_VERSION }}' # the target branch of the mono-repository which should be sliced (depends on the pushed branch or tag)
          package_directory: '${{ matrix.package.local_path }}' # local path of the package from the matrix
          remote_repository: '${{ matrix.package.split_repository }}' # target repository of the package from the matrix
          remote_repository_access_token: 'x-access-token:${{ steps.app-token.outputs.token }}' # an access token for the target repository (optional)
